### ISSUE TITLE
mysql utilities updated?

### ISSUE THREAD

**Issue by rjjanuary** [alorenzo175/mylogin#1]
First of all, thank you for writing this.  It is likely to fulfill a need within my organization.  I did notice that as of my_print_defaults v 1.6 the password is shown redacted by default.  To show the actual pass you have to supply the '-s' flag.  

``` bash
-bash-4.1$ my_print_defaults --version
my_print_defaults  Ver 1.6 for Linux at x86_64

-bash-4.1$ my_print_defaults test
--user=rjanuary
--password=*****
--host=localhost
--port=3306

-bash-4.1$ my_print_defaults test -s
--user=rjanuary
--password=Secure_Password1
--host=localhost
--port=3306
```

``` python
-bash-4.1$ python
Python 2.6.6 (r266:84292, Jul 23 2015, 05:13:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mylogin
>>> mylogin.get_login_info('test')
{'passwd': u'*****', 'unix_socket': 'localhost', 'host': u'localhost', 'user': u'rjanuary', 'port': 3306}
>>> exit()
```

This is easily avoided by adding the '-s' to the command line on line 296 of my_print_defaults.py

Is this intentional, or have the mysql utilities been updated?

**Comment by alorenzo175** [comment]
Sorry about not getting around to this sooner. MySQL likely changed this for security reasons since [5.6.25](http://dev.mysql.com/doc/refman/5.6/en/my-print-defaults.html). At any rate, I should have a workaround that tries the `-s` option first, and falls back if that fails.
